# see https://docs.searxng.org/admin/engines/settings.html#use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "fd9a1d1c9bb844ebeaf7dfabe5c5ce797a49a554768e2f857053ca43c577072d"  # change this!
  limiter: false
  image_proxy: true
general:
  debug: true
search:
  formats:
    - html
    - json
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0